version: '1.0'
name: update
displayName: update
triggers:
  trigger: auto
  #schedule:
    #- cron: '* 0 */6 * * ? *'
variables:
  global:
    - TOKEN
stages:
  - name: update
    displayName: 更新
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: update_files
        displayName: 更新文件
        nodeVersion: 21.5.0
        commands:
          - git clone https://dream-deve:${TOKEN}@gitee.com/dream-deve/migu_video.git
          - cd migu_video
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 执行编译命令 '
          - npm install && node fetchURLByAndroid720p.js
          - git config user.name "Gitee流水线"
          - git config user.email "actions@githee.com"
          - git add .
          - '# gitee流水线提交 '
          - git diff --quiet && git diff --staged --quiet || git commit -m "Update by Gitee流水线"
          - git push
        caches: []
        notify: []
        strategy:
          retry: '0'
          timeout: 4
